###
POST http://localhost:5192/auth/signup
Content-Type: application/json

{
    "Email": "test@gmail.com",
    "Lastname": "Jane",
    "FIrstname": "Doe",
    "Password": "1234"
}

###
POST http://localhost:5192/auth/login
Content-Type: application/json

{
    "Email": "test@gmail.com",
    "Password": "1234"
}

###
GET https://localhost:7140/jokes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0QGdtYWlsLmNvbSIsImp0aSI6IjNkOWM5MTJiLWJhZjktNGVkMS04NzIwLWFhNDJkNGNlNzE0OSIsImV4cCI6MTc3Nzg5MTkxOSwiaXNzIjoibG9jYWxob3N0IiwiYXVkIjoidXNlciJ9.9fBobmS_lrFus2v9IIioMir5fdx5xDzvuZvSJ5IK6k4


###
GET https://api.api-ninjas.com/v1/dadjokes
X-Api-Key: 7Nlbd9YrlfgPnYjycG04dd4iAOsI26sVjWH1RS0a

