###
POST http://localhost:5192/auth/signup
Content-Type: application/json

{
    "Email": "test@gmail.com",
    "Lastname": "Jane",
    "FIrstname": "Doe",
    "Password": "1234"
}

###
POST http://localhost:5192/login
Content-Type: application/json

{
    "Email": "test@gmail.com",
    "Password": "1234"
}