###
POST http://localhost:5192/auth/signup
Content-Type: application/json

{
    "Email": "test@gmail.com",
    "Lastname": "Jane",
    "FIrstname": "Doe",
    "Password": "1234"
}

###
POST http://localhost:5192/auth/login
Content-Type: application/json

{
    "Email": "test@gmail.com",
    "Password": "1234"
}

###
GET https://localhost:7140/jokes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0QGdtYWlsLmNvbSIsImp0aSI6Ijc3NjBiNTA1LTEzNmUtNDQ5My1hMDdiLTQ4NTBmNTZkM2EzYyIsImV4cCI6MTc3NzkwOTMxOSwiaXNzIjoibG9jYWxob3N0IiwiYXVkIjoidXNlciJ9.njJXFs879tXh-NUzPbESK-svWzhYihwU3DSF7qfM9bo


###
GET https://api.api-ninjas.com/v1/dadjokes
X-Api-Key: 7Nlbd9YrlfgPnYjycG04dd4iAOsI26sVjWH1RS0a

